### PR TITLE
1446 remove ltc button from notes main menu and include LTC scripts in alpha categories

### PR DESCRIPTION
**Pull request by MeganGeissler**
Removed LTC button from Notes Main Menu
Updated ChangeLog to notify users of this change.
No action required for CLOS or ? for sharepoint documents.
Did not rename, left LTC in the naming for now.

### CODE REVIEW

**Review by IlseFerris — CHANGES_REQUESTED** [review]
Hey Megan, I should have mentioned this before but there's some handling in the COMPLETE LIST OF SCRIPTS that should also get updated. Instructional links might be the only thing, but check with @courtrightd as well.

**Comment by MeganGeissler** [comment]
@IlseFerris I updated CLOS but check it out in case there is a better way to update this.

**Comment by MeganGeissler** [comment]
@IlseFerris I reverted CLOS so I can merge this separately after I pull a fresh copy of the CLOS

**Review by IlseFerris — APPROVED** [review]
I approve thee!

**Pull request merged**
