### PR TITLE
1898 NAV - FIND MMIS PMI IN MAXIS & FIND MAXIS CASE IN MMIS, update script functionality

### PR DESCRIPTION
**Pull request by MDR22**
Update both scripts to align with current scripting standards. Updated FIND MMIS PMI IN MAXIS to end at DSPL panel instead of navigating to CASE/NOTE. Updated the function navigate_to_MMIS_region to make it work with MMIS training region.

### CODE REVIEW

**Comment by C-Love** [comment]
@MDR22 - Question about the training region support. Do both scripts support the training region? Or is it just MMIS to MAXIS? With that support, is the expectation that the session only has production OR Training, and not both?

**Comment by MDR22** [comment]
> @MDR22 - Question about the training region support. Do both scripts support the training region? Or is it just MMIS to MAXIS? With that support, is the expectation that the session only has production OR Training, and not both?

Both scripts have training to training support and production to production support. The MMIS to MAXIS script has "simpler" handling for determining whether to navigate to training or production as it doesn't check all windows the way the MAXIS to MMIS function does. I could create a function for MMIS to MAXIS so that it operates in the same way. 

And yes, I kept the functionality where it will only work if production OR training is open, but not both. I couldn't think of way to determine whether the user is in training or production without navigating to SELF, which I thought might disrupt the user if they wanted to stay at a certain panel when navigating from MAXIS to MMIS.

**Comment by C-Love** [comment]
Ok - I think I found the issue I was having. The redirects that the buttons are not set up to run locally. Once I ran it directly, it worked as expected for the training option once I ran it directly.

**Review by C-Love — APPROVED** [review]
Looks good to me!

**Review by MeganGeissler — APPROVED** [review]

**Pull request merged**
