### PR TITLE
#1622 SNAP Waived Interview Return Contact added to Client Contact

### PR DESCRIPTION
**Pull request by C-Love**
Added functionality to Client Contact to review for the 'Info Needed' CASE/NTOE created by SNAP Waived Interview to alert the worker to the questions that info needed has listed. This will allow Client Contact to redirect to SNAP Waived Interview to specifically support the Return Contact information needed. 

Pull request is scheduled to be merged on Tuesday mid day after the HT is released. 

Only additional update will be to CLOS with the HT date in the script array. Will wait until Tuesday to do this, and do it on this pull but if there is a merge issue, we can create a new pull for that specifically.

### CODE REVIEW

**Comment by C-Love** [comment]
Ooooohhh! I just had a thought! We could add in the function that records functionality to know if we are redirecting from Client Contact. 

Need to think about the naming convention on using the new function but this could be a good test case of data on functionality specifically.

**Review by IlseFerris — APPROVED** [review]
Successfully ran on pending training case 334781. I approve thee for Tuesday's release.

**Comment by MeganGeissler** [comment]
Looks good! Only thing I ran into is the write-in for Q10. wasn't writing into the casenote.

**Review by MeganGeissler — APPROVED** [review]
Woops put my comment in the wrong place so putting it here too..

Return Contact looks good! When running waived interview with the CAF form, Q10's write in didn't seem to display in casenotes.

**Comment by courtrightd** [comment]
I have fixed the issue with Jobs question (q10) write-in info. 
Also fixes it to only write SNAP interview dates
Minor format fixes to work rules dialog.
I tested, but if anyone wants to run it one more time that would be great.

**Review by courtrightd — APPROVED** [review]
Tested and looking good from my end!

**Review by MeganGeissler — APPROVED** [review]
Tested on a few and looks good!

**Pull request merged**
