### PR TITLE
1993 notes interview rights and responsibilities

### PR DESCRIPTION
**Pull request by MeganGeissler**
Shortened rights and responsibilities dialog verbiage 
Checkbox feature should be setup to work with the save_work function.

### CODE REVIEW

**Review by MDR22 — APPROVED** [review]
Sent through some minor edits directly. Otherwise, looks good!

**Comment by C-Love** [comment]
The way the checkboxes read aren't going to be particularly clear to a screen reader. I know we don't have the best ADA compliance, but phrasing checkboxes with 'Check here if ...' helps people who might use a screen reader to interact with the scripts. The functionality all worked and I think the phrasing is really helpful. 

Only other nitpicky thing is to add a space after the dash for the bullet, text always feels tight as is.

**Review by C-Love — APPROVED** [review]
Looks great!

**Review by courtrightd — APPROVED** [review]
This looks great. I hereby grant my enthusiastic approval!

**Pull request merged**
