### PR TITLE
#441 & #445 Updates to the CAF Script for processing the HUF and waiving interviews

### PR DESCRIPTION
**Pull request by C-Love**
Updates to the CAF script:
 - Adding HUF as a form option
 - Making sure Application isn't selected for a HUF
 - Preventing the 'Interview Completed' case note
 - Creating a specific waived interview note 
 - Remove the old REVW dates adjustment code.

### CODE REVIEW

**Review by IlseFerris — CHANGES_REQUESTED** [review]
Can we add the renewal month to the header of the interview waived case note?
And then take out the mystery box edit box :)

**Comment by C-Love** [comment]
Fixed bug with the mystery editbox.

**Comment by C-Love** [comment]
Added the review month and year to the CASE NOTE by program.

**Comment by C-Love** [comment]
@IlseFerris ok - this is really done now and you saw it function in the meeting. Any other changes you want to see before I pull it in?

**Comment by C-Love** [comment]
I merged this ALSO REBASE WORKED

**Pull request merged**
