### PR TITLE
Snap banked months scrub

### PR DESCRIPTION
**Pull request by IlseFerris**
Updates to scripts and functions from issue #419. Initial tested, but I'd love some fresh eyes in case I miss anything.

### CODE REVIEW

**Comment by C-Love** [comment]
@IlseFerris In the CAF script there is a dialog that allows for manual entry of the Banked Months.
image
Do you want to leave that as is? With the changes to the rest of the script anything entered there would not end up on the main dialog or in the case notes.

**Comment by C-Love** [comment]
Another question - Do we need the ABAWD FIATer right now?

**Comment by C-Love** [comment]
Final question - are we no longer concerned with sending 'ABAWD FS RULES' - was that specific to BM?

Also - all questions can be addressed at the meeting.

**Comment by IlseFerris** [comment]
@C-Love I updated the CAF script to remove the banked months field. 
All other questions we addressed yesterday. Can you take a quick look at my latest commit?

**Review by C-Love — APPROVED** [review]
Awesome. Looks good. And while you have commented most of it out... can we hope that these never come back in this way.

**Pull request merged**
