### PR TITLE
#504 FuncLib - county_list - commented out about 20 small counties

### PR DESCRIPTION
**Pull request by C-Love**
I've updated the county_list in Functions Library and tested it out in NOTES - Returned Mail. 

This is only a change to a reserved variable for a drop list box/ combo box. 

No new functionality.

### CODE REVIEW

**Review by IlseFerris — COMMENTED** [review]
What about the interview script @C-Love?!?!?

**Comment by IlseFerris** [comment]
Hey here's a comment

**Comment by C-Love** [comment]
Oh right! Interview - let me do that real quick

**Review by MiKaylaH22 — COMMENTED** [review]
I reviewed and it is lovely

**Pull request merged**
