### PR TITLE
#1600 DAIL - New Hire NDNH, ensure script returns to DAIL message

### PR DESCRIPTION
**Pull request by MDR22**
Add handling to ensure that script returns to same DAIL message if user navigates to a different panel during dialog. Updated function nav_in_dail to read full DAIL message to ensure exact match is found in situations where the shortened DAIL message may have duplicates.

### CODE REVIEW

**Review by courtrightd — COMMENTED** [review]
Needs something before writing the "T" at line 92 to make sure its actually in a DAIL message. Emailed details.

**Comment by MDR22** [comment]
Added additional handling to ensure the script could navigate back to HIRE message and move through DAIL

**Review by C-Love — APPROVED** [review]
Looks good to me, I didn't try it but I think it's solid. I say go for it.

**Review by courtrightd — APPROVED** [review]
Tested, working good!

**Pull request merged**
