### PR TITLE
#1495 Add handling for names with extra spaces

### PR DESCRIPTION
**Pull request by MDR22**
Add handling for instances on ABPS panel where there are extra spaces between multiple last names

### CODE REVIEW

**Comment by C-Love** [comment]
Hey @MDR22 - the function has been added to the CAF script here - is there a reason it isn't just updated in the functions library.

**Comment by MDR22** [comment]
> Hey @MDR22 - the function has been added to the CAF script here - is there a reason it isn't just updated in the functions library.

That was a mistake. I only intended to make the update in the functions library. The edits to the CAF script were part of testing. I will fix that!

**Comment by MDR22** [comment]
@C-Love I updated the pull request to only include update to function in functions library.

**Comment by C-Love** [comment]
Awesome! This is also great because I was afraid we were going to have a merge conflict.

**Review by C-Love — APPROVED** [review]
Looks good!

**Pull request merged**
