### PR TITLE
1369 ex parte tikl support 

### PR DESCRIPTION
**Pull request by IlseFerris**
Partial issue pull request. @MDR22 take a look at the function non_actionable_dails to see which DAIL's are also excluded from assignment.

### CODE REVIEW

**Comment by MDR22** [comment]
> Partial issue pull request. @MDR22 take a look at the function non_actionable_dails to see which DAIL's are also excluded from assignment.

Helpful to see all of the excluded DAILs! Does this DAIL message need to get added to the non_actionable_dails function? Or is that unnecessary since it is noted as not actionable within this script?

**Comment by IlseFerris** [comment]
That's correct. It wasn't added to the function since at this point we don't want it to be deleted, and that function is used in our scripts that delete as well.

**Comment by IlseFerris** [comment]
Is this pull request a go @MDR22?

**Comment by MDR22** [comment]
Yes, sorry! I commented but didn't approve. Looks good.

**Pull request merged**
